### ISSUE TITLE
Provide a default implementation of Matcher protocol for Object class

### ISSUE THREAD

**Issue by alan-ghelardi** [nubank/matcher-combinators#100]
Very often I run into situations where, due to some circumstances, the data structures that I'm comparing through matcher-combinators contain some values for which there is no implementation of the Matcher protocol and the test throws an exception (e.g. java.io.File, java.time.Instant, etc.).

Is there any reason for not providing a default implementation of the Matcher protocol for the Object class, that could match values through their equality? For example: 
```clojure
(extend-protocol matcher-combinators.core/Matcher
  Object
  (match [expected actual]
    (= expected actual)))
```
Not sure whether there are known implications against this approach.

**Comment by philomates** [comment]
That is a great suggestion!
I tested it out and it didn't seem to break any tests (other than the ones that check that matching objects failed), so I went ahead and turned it into a PR: https://github.com/nubank/matcher-combinators/pull/103

**Comment by alan-ghelardi** [comment]
Awesome @philomates! Thank you so much for the prompt answer.

**Comment by philomates** [comment]
resolved in https://github.com/nubank/matcher-combinators/pull/103
