### ISSUE TITLE
Matching against `java.util.HashSet` doesn't work

### ISSUE THREAD

**Issue by gabrielgiussi** [nubank/matcher-combinators#116]
### The problem

I spend some time debugging why a test passed if I were using `=` but failed if I were using `match?` instead, what doesn't make sense since `match?` should be more permissive.
The output was something like this, which was confusing for me:
```clojure
#:matcher-combinators.result{:type :mismatch,
                             :value #matcher_combinators.model.Mismatch{:expected #{1 2}, :actual #{1 2}},
                             :weight 1}
```

After some debugging I found the cause and it was that the expected set was a `java.util.HashSet` and this doesn't pass the predicate `set?` used in the `validate-input`
https://github.com/nubank/matcher-combinators/blob/93eabde02940d8bf7a2e15fc0f1e77b7aefe97c0/src/cljc/matcher_combinators/core.cljc#L333-L337

If you use the java set as the actual result it will fail but it is clear what is happening, although I don't know if the user should be faced with this kind of error, there is a better feedback that we could provide to they?
```clojure
No implementation of method: :match of protocol: #'matcher-combinators.core/Matcher found for class: java.util.HashSet
```

### What to do?

I'm not sure if `match?` should handle this case, because it requires too much work, but at least it would be nice to provide a better error message.

### Namespace to reproduce this stuff

```clojure
(ns spaceteam.db.datomic.a
  (:require [matcher-combinators.standalone :refer [match?]]
            [matcher-combinators.core :as core]))


(def clojure-set #{1 2})

(def java-set (doto (new java.util.HashSet) (.add 1) (.add 2)))

(= clojure-set java-set)
; => true

(match? clojure-set java-set)
; => false

#_(match? java-set clojure-set)
; This fails with 'No implementation of method: :match of protocol: #'matcher-combinators.core/Matcher found for class: java.util.HashSet'

(core/match clojure-set java-set)
; => #:matcher-combinators.result{:type :mismatch,
;                             :value #matcher_combinators.model.Mismatch{:expected #{1 2}, :actual #{1 2}},
;                             :weight 1} 
```

**Comment by dchelimsky** [comment]
> I'm not sure if match? should handle this case, because it requires too much work

`matcher-combinators` already has explicit support for some java types here: https://github.com/nubank/matcher-combinators/blob/93eabde02940d8bf7a2e15fc0f1e77b7aefe97c0/src/cljc/matcher_combinators/dispatch.cljc#L63-L97

Adding support for `java.util.HashSet` _should_ be a matter of adding one entry to that map.

**Comment by dchelimsky** [comment]
PR #125 is addressing this. Closing.
