### ISSUE TITLE
Match complex data structures like datascript

### ISSUE THREAD

**Issue by darkleaf** [nubank/matcher-combinators#120]
I want to match [datascript](https://github.com/tonsky/datascript/) values and watch highlighted wrong datoms.

```clojure
(let [a (-> (d/empty-db)
            (d/db-with [{:a :b}
                        {:c :d}]))
      b (-> (d/empty-db)
            (d/db-with [{:a :b}
                        {:c :wrong}]))]
  (m/match a b))
```

I can offer several solutions:

1. In my app I can extend DB with Matcher protocol. DB can be transformed into a seq.

```clojure
(extend-protocol m/Matcher
  datascript.db.DB
  (match [this actual]
    (if (d/db? actual)
      (m/match (seq this) (seq actual))
      (m/match this actual))))
```

2. map/fmap/transform/view/lens matcher

```clojure
;; matchers/map :: predicate -> transform-fn -> matcher -> matcher
(match? (matchers/view d/db? seq [(d/datom 1 :attr :val)]) some-db)
```

3. When a matcher is an object and implements `clojure.data/Diff`  report mistake as a new Diff model.  

Also, I want to match exceptions and the second variant seems to be better.

**Comment by fernando-nubank** [comment]
> Also, I want to match exceptions and the second variant seems to be better.

Could you provide an example, please?

**Comment by darkleaf** [comment]
> Could you provide an example, please?

```clojure
(match? (matchers/view smth/throwable? Throwable->map {:message "Something went wrong"
                                                       :data {:some-data int?}})
        (ex-info "Something went wrong" {:dome-data 42}))
```

**Comment by philomates** [comment]
`thrown-match?` exists to match exceptions if that helps
https://github.com/nubank/matcher-combinators/#clojuretest  / https://github.com/nubank/matcher-combinators/blob/master/src/cljc/matcher_combinators/test.cljc#L15-L17

**Comment by darkleaf** [comment]
I'm developing a library that's allowed to describe and to test side effects. 
https://github.com/darkleaf/effect/blob/master/test/darkleaf/effect/script_test.cljc#L116

**Comment by darkleaf** [comment]
Another (4) solution is handling [`p/Datafiable`](https://github.com/clojure/clojure/blob/master/src/clj/clojure/datafy.clj#L45) values.
