### ISSUE TITLE
Match vectors with functions by its equality

### ISSUE THREAD

**Issue by darkleaf** [nubank/matcher-combinators#121]
How can I match vectors with functions?

```clojure
(match? [:session/swap + 2] [:session/swap + 2]) ;; error
(match? [:session/swap (m/equals +) 2] [:session/swap + 2]) ;; ugly
(match? (m/= [:session/swap + 2]) [:session/swap + 2]) ;; I want something like this 
```

**Comment by fernando-nubank** [comment]
It is possible to add a default matcher for `Ifn` and set it to be `m/equals`.
Comparing functions is hard and, for example, we can't compare anonymous functions.
For example, 
```clojure
(= + +) ;; => true
(= (partial + 1) (partial + 1) ) ;; => false
``` 
This is strange for a clojure programmer because we are used to compare values and not "instances".  :thinking:

**Comment by darkleaf** [comment]
> It is possible to add a default matcher for Ifn and set it to be m/equals.

It conflicts with existing [Fn](https://github.com/nubank/matcher-combinators/blob/master/src/cljc/matcher_combinators/parser.cljc#L99-L102) implementation.

> Comparing functions is hard and, for example, we can't compare anonymous functions.

Yes.  Maybe I can use vars instead of functions `[:session/swap #'+ 2]`. Any way I want to match structures with `=` function and to watch problem details.

**Comment by fernando-nubank** [comment]
> It conflicts with existing Fn implementation.

Yes, you're right. All functions are treated as predicates.

> Maybe I can use vars instead of functions

The current implementation for `Var` use `m/equals` so it will not work with your example:
```clojure
(match? #'+ +) ;; => false
(match? #'+ #'+) ;; => true
```
I guess you could override the `Var` definition inside your project to check against `(get-value var)`.
I don't see any feasible implementation/API for what you are asking for :disappointed:

**Comment by darkleaf** [comment]
Ok. Thanks.

**Comment by dchelimsky** [comment]
@darkleaf there are two tools I think you can use to extend matcher-combinators for this case:

* https://github.com/nubank/matcher-combinators/blob/859de1c350cd98d512b2ac45748904a7c8044ff9/src/clj/matcher_combinators/clj_test.clj#L165
* https://github.com/nubank/matcher-combinators/blob/859de1c350cd98d512b2ac45748904a7c8044ff9/src/clj/matcher_combinators/clj_test.clj#L74

The challenge with either is that you'd have to change how matcher-combinators interprets functions (which it treats as predicates by default), so you wouldn't be able to do e.g.

```clojure
(my-special-match? [:a + odd?] [:a + 3])
```
