### ISSUE TITLE
`seq-of` matcher

### ISSUE THREAD

**Issue by dchelimsky** [nubank/matcher-combinators#149]
Add a matcher that matches a non-empty sequence of elements that match a supplied matcher, e.g.

```clojure
(match? (seq-of {:name string? :id uuid?})
        [{:name "Michael"
         :id    #uuid "c70e35eb-9eb6-4e3d-b5da-1f7f80932db9"}])
```

This impl works, but the resulting failure message leaves something to be desired:

```clojure
(defn seq-of [matcher] (fn [coll] (and (seq coll) (every? (partial matcher-combinators.standalone/match? matcher) coll))))
```

**Comment by philomates** [comment]
giving it a shot in https://github.com/nubank/matcher-combinators/pull/191, what do you think?
