### ISSUE TITLE
undeclared Var warning in ClojureScript  

### ISSUE THREAD

**Issue by thumbnail** [nubank/matcher-combinators#154]
After updating to the latest matcher-combinators  (3.1.3 at the time of writing), I noticed a warning popped up in our clojurescript test suite:

> WARNING: Use of undeclared Var matcher-combinators.matchers/Absent at line 169 target/out/matcher_combinators/matchers.cljc

This was introduced in #152.

**Comment by philomates** [comment]
thanks for reporting @thumbnail , a fix should be released in `3.1.4`
