### ISSUE TITLE
Proposal: annotate colored mismatch information with `expected` and `actual`

### ISSUE THREAD

**Issue by philomates** [nubank/matcher-combinators#161]
Mismatch information in a test failure is printed such that the `expected` data is in yellow and the `actual` data is in red.
I almost always can't remember if yellow is `expected` or `actual`. I imagine others encounter the same trouble.

To help us remember what is what, I thought we could annotate the yellow data in a `(expected ..)` and the red data in `(actual ..)`

If folks like this idea I'll open a patch for it.

The only downside I can imagine is more information in mismatch output, which could add to cluttered feeling

### before

![before](https://user-images.githubusercontent.com/94817/122896907-d3895c00-d349-11eb-87a4-df34f813183b.png)

### after

![after](https://user-images.githubusercontent.com/94817/122896918-d5ebb600-d349-11eb-938b-5ecf834508c8.png)

**Comment by philomates** [comment]
This would also address https://github.com/nubank/matcher-combinators/issues/17

**Comment by gabrielgiussi** [comment]
I find this helpful and without disadvantages, open a PR! 

> I almost always can't remember if yellow is expected or actual

I've been there

**Comment by philomates** [comment]
addressed in https://github.com/nubank/matcher-combinators/pull/163
