### ISSUE TITLE
clj-kondo exports

### ISSUE THREAD

**Issue by vemv** [nubank/matcher-combinators#176]
I was getting clj-kondo `:unresolved-symbol` warns which the following would fix:

```clj
:unresolved-symbol {:exclude [(clojure.test/is [match?])]}
```

It might be worthwhile to add a "kondo exports" file with that. Or at least mention it in the readme if you'd rather avoid the "side effect".

Cheers - V

**Comment by ericdallo** [comment]
Fixed by #192
