### ISSUE TITLE
Implement matcher for checking a property against some or all of the sequence values

### ISSUE THREAD

**Issue by philomates** [nubank/matcher-combinators#18]
similar to midje's [`has`](https://github.com/marick/Midje/wiki/Checking-sequential-collections#has-checks-a-property-against-some-or-all-of-the-sequence-values)

This might not fit well with the approach that `matcher-combinators` takes, depending on the actual data-structure. Could potentially handle this with infinite series `(match (repeat odd?) [1 3 5])`

**Comment by dchelimsky** [comment]
@philomates doesn't `(embeds [m1 m2 ,,,] <sequence>)` cover this? Or am I missing something?

**Comment by philomates** [comment]
yeah, I think so. This wasn't really a fleshed out idea, just an observation by a colleague that I turned into an issue. Going to close it out
