### ISSUE TITLE
Consider adding a deps.edn

### ISSUE THREAD

**Issue by lread** [nubank/matcher-combinators#188]
## Currently
matcher-combinators only has a `project.clj`

## Opportunity
Adding a `deps.edn` allows for easy:
- access to unreleased works-in-progress to support testing via git dep
- access to works-in-progress locally via `:local\root` dep

## Next steps
If you think this is a good idea, happy to help with a PR.

## Related
#174 - I would think a `deps.edn` would not reference midje.

**Comment by philomates** [comment]
thanks for the suggestion, excited to get all the goodness of the `deps.edn` tooling.
Addressed in https://github.com/nubank/matcher-combinators/pull/197
