### ISSUE TITLE
sequence-match reports seqs in reverse order

### ISSUE THREAD

**Issue by plexus** [nubank/matcher-combinators#39]
Consider this test

``` clojure
(deftest sequence-match-test
  (is (match? [1 2 3] (list 1 2 4))))
```

This is reported as:

```
FAIL in (sequence-match-test) (randomize_test.clj:53)
mismatch:
((mismatch 3 4) 2 1)
```

The order of the elements in the list has been reversed, which can be very confusing. The culprit is `matcher_combinators/core.clj:102`

``` clojure
          [:mismatch (into (empty actual) (map value match-results))]
```

By using `into` elements get inserted by a series of `conj` calls, which in the case of a list/seq prepends, rather than appends.

I'm not sure what the best solution is, you could drop the type and simply return `(map values match-result)`. You could add a specific check for seq/list, and reverse the result, but then you'll get a `PersistentList` no matter what the input type. 

I guess the main use case here is to report vectors as vectors, and other seq types as seqs/lists, so maybe turn it around and only use `into` when dealing with a vector.

Or you could get fancy :)

``` clojure
(let [insert-in-order? (= [1 2] (into (empty actual) [1 2]))]
   (cond->> (map value match-result) insert-in-order? (into (empty actual)))
```

**Comment by phillipm** [comment]
Thanks for reporting the issue and diving in to find the underlying subtleties!

The type preservation is solely to distinguish between `[1 2 3]` and `(1 2 3)` when reporting mismatches, so it doesn't matter what type of list it is as long as square brackets are used for vectors (context in https://github.com/nubank/matcher-combinators/issues/13)

Maybe not the most elegant, but I've fixed it in https://github.com/nubank/matcher-combinators/pull/41 and will release it now

**Comment by plexus** [comment]
Looks good, thanks!
