### ISSUE TITLE
Embeds for `seq` does not work like `(contains :in-any-order :gaps-ok)`

### ISSUE THREAD

**Issue by oporkka** [nubank/matcher-combinators#47]
I am using matcher-combinators 0.3.1, and comparing Midje's
```
  (fact "contains :in-any-order :gaps-ok"
    [1 2 3 4 5 6] => (contains [1 5]
                               :in-any-order
                               :gaps-ok))
```
to
```
  (fact "m/embeds"
    [1 2 3 4 5 6] => (match (m/embeds [1 5])))
```
The version with `contains :in-any-order :gaps-ok` passes, but the latter one with `embeds` does not pass.  The README says for `embeds` that:

- sequence: order-agnostic matcher that will match when provided a subset of the expected sequence. Similar to midje's `(contains expected :in-any-order :gaps-ok)`

It seems that there's either a mismatch in the implementation or the documentation.

**Comment by phillipm** [comment]
Indeed, very strange! Thanks for reporting, I'm going to try to get this sorted

**Comment by phillipm** [comment]
Resolved in https://github.com/nubank/matcher-combinators/pull/48 and deployed as `0.3.2`. Cheers!
