### ISSUE TITLE
Provide built-in support for matching exception data 

### ISSUE THREAD

**Issue by alan-ghelardi** [nubank/matcher-combinators#56]
I think that having built-in support for using matchers with exception data would be very helpful. I've poorly implemented something similar due to a need here: https://github.com/nubank/midje-nrepl/blob/master/test/midje_nrepl/formatter_test.clj#L115. 

An initial idea would be a more sophisticated version of the aforementioned function in the namespace `matcher-combinators.midje` and an equivalent one in the namespace `matcher-combinators.test` with support for `clojure.test`.

I can open a pull request to be analyzed, but I'd like to hear your opinion about the topic. Do you think that something in that direction makes sense?

**Comment by philomates** [comment]
Hey @alan-ghelardi, good suggestion and sorry for the delay on responding!
I actually hadn't come across the need until today when migrating a service from midje to clojure.test. I decided to implement it myself to unblock that work, so you can find it in the `0.6.0` release (via https://github.com/nubank/matcher-combinators/pull/61)
