### ISSUE TITLE
Match `embeds` are very slow in this specific case

### ISSUE THREAD

**Issue by RafaeLeal** [nubank/matcher-combinators#63]
Hi!

For some reason, this test is very slow.. almost 1 minute.

```clojure
(fact "something is slow"
      [{:a {:a "a",
            :b "b",
            :c "c",
            :d "d",
            :e "e",
            :f "f"}}
       {:a {:a "a",
            :b "b",
            :c "c",
            :d "d",
            :e "e",
            :f "f"}}
       {:a {:a   "foo",
            :b ["-c" "some-string"]}}
       {:a {:a   "foo",
            :b ["-c" "some-string-2"]}}
       {:a {:a   "foo",
            :b ["-c" "some-string-3"]}}
       {:a {:a   "foo",
            :b ["-c" "some-string-4"]}}
       {:a {:a   "foo",
            :b ["-c" "some-string-5"]}}
       {:a {:a   "foo",
            :b ["-c" "some-string-6"]}}
       {:a {:a   "foo",
            :b ["-c" "some-string-7"]}}
       {:a {:a   "foo",
            :b ["-c" "some-string-8"],
            :c    "good"}}] => (match (embeds [{:a {:a "foo" :b ["-c" "some-string-5"]}}])))
```

lein midje matchers-slow  51.11s user 1.54s system 108% cpu 48.531 total
lein midje matchers-slow  49.41s user 1.59s system 107% cpu 47.334 total
lein midje matchers-slow  52.27s user 1.70s system 107% cpu 50.197 total

while running with
```clojure
(match [anything
              anything
              anything
              anything
              anything
              anything
              {:a {:a "foo" :b ["-c" "some-string-5"]}}
              anything
              anything
              anything])
```
lein midje matchers-slow  15.62s user 1.22s system 122% cpu 13.777 total

**Comment by philomates** [comment]
Hey @RafaeLeal thanks for reporting. When implementing some of the matchers I decided to use some algorithms with really bad BigO factors; deciding to get more comprehensive matching at the cost of runtime speed.
My intention was to revisit the decisions if anyone noticed things getting slow, which it appears you've noticed.

I'll try to take a look at this soon, but probably won't get a chance in the next week or two

**Comment by philomates** [comment]
Thanks for reporting @RafaeLeal. I'm pretty sure I've fixed it in https://github.com/nubank/matcher-combinators/pull/72 which has been deployed as `0.8.2`
