### ISSUE TITLE
Cursive integration not working

### ISSUE THREAD

**Issue by fbeline** [nubank/matcher-combinators#77]
The cursive command "Run tests in current NS in REPL" does not report errors/failures.

As far as I can say seems that the [customs report](https://github.com/nubank/matcher-combinators/blob/5e27668ce5827c75260439cc794e633415928fe6/src/clj/matcher_combinators/clj_test.clj#L88) functions are not being considered.

cursive version: 1.8.1-2018.2

**Comment by philomates** [comment]
Hey Felipe, thanks for reporting. This one actually got flagged a while ago in https://github.com/nubank/matcher-combinators/issues/31 so let's track the issue there
