### ISSUE TITLE
Performance issue matching two lists with (match (m/in-any-order)) 

### ISSUE THREAD

**Issue by MarcoNicolodi** [nubank/matcher-combinators#79]
Hi there!

We noticed our unit tests suite has become a lot slower after merging https://github.com/nubank/gocd-config-dsl/pull/1211

We investigated and noticed that this test was the cause https://github.com/nubank/gocd-config-dsl/pull/1211/files#diff-ff9b62082ef0137d39769d1719efcaea

It uses `(match (m/in-any-order))` to match two lists:

Extracting the result out of the unit under test, this is the resulting matching:

```clojure
({:name :shore,
  :environments {:staging #{:s0}, :prod #{:s0}},
  :pipelines #{{:type :clojure-service, :prod {:promotion :automatic}, :cdc-test-frameworks #{:sachem}}}}
 {:name :pokedex,
  :deprecated {:kafka true, :type :jetty},
  :environments {:staging #{:s0 :s1 :s2}, :prod #{:s7 :s6 :s0 :s8 :s4 :s9 :s10 :s1 :s5 :s3 :s2}},
  :pipelines #{{:type :clojure-service, :cdc-test-frameworks #{:sachem}, :prod {:promotion :automatic}}
               {:type :service-config}}})  
=> (match (m/in-any-order '({:name :pokedex,
                                 :deprecated {:kafka true, :type :jetty},
                                 :environments {:staging #{:s0 :s1 :s2}, :prod #{:s7 :s6 :s0 :s8 :s4 :s9 :s10 :s1 :s5 :s3 :s2}},
                                 :pipelines #{{:type :clojure-service, :cdc-test-frameworks #{:sachem}, :prod {:promotion :automatic}}
                                              {:type :service-config}}},
                                {:name :shore,
                                 :environments {:staging #{:s0}, :prod #{:s0}},
                                 :pipelines #{{:type :clojure-service, :prod {:promotion :automatic}, :cdc-test-frameworks #{:sachem}}}})))))
```

**Comment by philomates** [comment]
Hey Marco, thanks for reporting. It looks like it is related to https://github.com/nubank/matcher-combinators/pull/71 and https://github.com/nubank/matcher-combinators/pull/76 

The issue was introduced in `0.8.2` (https://github.com/nubank/matcher-combinators/pull/72/) so if you revert to a version before that one you should be fine.

I haven't had time to fix it yet and might just revert https://github.com/nubank/matcher-combinators/pull/72, but have been hesitant because that PR fixes other slowness issues

**Comment by markomafs** [comment]
@philomates Are we considering doing a perfomance test suit? 
I'm not sure which is the best library for that, not even sure if we need it, but it could be a way out for having this "short blanket" issue.

**Comment by philomates** [comment]
addressed in https://github.com/nubank/matcher-combinators/pull/87, sorry about the delay on this
