### ISSUE TITLE
`match?` seems to freeze cider

### ISSUE THREAD

**Issue by mpivaa** [nubank/matcher-combinators#88]
When running a test with `match?` on emacs test runner, cider freezies and can't get up, only restarting emacs solves. Kaocha works fine. Any ideas on how to debug?

**Comment by vemv** [comment]
I use a pretty old CIDER (as I tend to avoid upgrades) and while it works / doesn't freeze, running tests can easily result in false negatives, i.e. output will be green even if tests aren't passing.

This might be an additional signal pointing in the direction that something in the `matcher-combinators` impl might be slightly off.

(Worth noting, CIDER generally works with every test framework/helper, provided that it's built on top of `clojure.test` conventions)
