### ISSUE TITLE
Support matching negating an item in a Vector

### ISSUE THREAD

**Issue by markomafs** [nubank/matcher-combinators#99]
### Needs 
We have some cases where I want to match that an item is not present in a vector: 

i.e.: 
```clojure
(is (match? 
         (m/embeds [map1 (dont-want-this map2)]) 
         [map1 map2 map3]))
```
I didn't find it. 
Is there a way to do that?

**Comment by philomates** [comment]
So there isn't currently a way to do this.
I'm a little afraid that such behavior wouldn't be used often and might be a bit confusing, but this is mostly a feeling I have.

Reflecting on this a little, I wonder if it goes a bit against the declarative focus of matcher-combinators. Like usually with matcher-combinators you say "the data should look like this", and here you are saying it "shouldn't look like this". I don't know if this is an important distinction or how it plays out, but I guess it is interesting to reflect on. Also note that we already have `absent` in the context of specifying that a key in a map is absent, so it isn't like we're adhering to the constructionist declarative approach fully at the moment.

**Comment by markomafs** [comment]
Agree. 
I think we could approach this by discussing conceptually how matcher-combinators will position itself on this matter and the result would be: 
* we won’t support negative behavior and properly document it. 
* we will support and implement it. 


I’m available to discuss that.

**Comment by philomates** [comment]
https://github.com/nubank/matcher-combinators/pull/158 should implement this. 
To assert an entry doesn't appear in a vector you can now do
```
(testing "assert everything in the vector is an even number via negation (generally avoid this)"
  (is (match? (mismatch (embeds [odd?])) actual)))
```
